### ISSUE TITLE
How to use without bundling?

### ISSUE THREAD

**Issue by mrjacobbloom** [chrisguttandin/web-audio-beat-detector#172]
Is it possible to use this directly in the browser without a bundler or anything? Is there a pre-bundled version I can just drop into a script tag? This is what I'm trying:

```
import { analyze } from './node_modules/web-audio-beat-detector/build/esm/module.js';
```

And I'm getting this error:

```
Uncaught TypeError: Failed to resolve module specifier "web-audio-beat-detector-broker". Relative references must start with either "/", "./", or "../".
```

**Comment by chrisguttandin** [comment]
Hi @mrjacobbloom, unfortunately their is no build artifact which could be used directly in todays browsers.

You could use a service like StackBlitz instead to give it a try. https://stackblitz.com/edit/js-r81vzk?file=index.js Would that work for you?

**Comment by mrjacobbloom** [comment]
I'll give it a shot!

**Comment by mrjacobbloom** [comment]
jspm to the rescue, this worked:

```javascript
import WebAudioBeatDetector from 'https://dev.jspm.io/web-audio-beat-detector';
```

**Comment by chrisguttandin** [comment]
That's even better. I knew that there was something out there which can bundle packages on the fly but I couldn't find it anymore.
