### ISSUE TITLE
Use in plain nodeJS

### ISSUE THREAD

**Issue by psturm** [chrisguttandin/web-audio-beat-detector#199]
Trying to require in a simple nodejs script results in an error.

Usage:
```javascript
# script.js
const webAudioBeatDetector = require('web-audio-beat-detector');
```
Then simply run with `node script.js` results in:
```bash
<REDACTED-PATH>/node_modules/async-array-buffer/build/es5/bundle.js:8
	var worker = "!function(r){var n={};function o(e){if(n[e])return n[e].exports;var t=n[e]={i:e,l:!1,exports:{}};return r[e].call(t.exports,t,t.exports,o),t.l=!0,t.exports}o.m=r,o.c=n,o.d=function(e,t,r){o.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:r})},o.r=function(e){\"undefined\"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:\"Module\"}),Object.defineProperty(e,\"__esModule\",{value:!0})},o.t=function(t,e){if(1&e&&(t=o(t)),8&e)return t;if(4&e&&\"object\"==typeof t&&t&&t.__esModule)return t;var r=Object.create(null);if(o.r(r),Object.defineProperty(r,\"default\",{enumerable:!0,value:t}),2&e&&\"string\"!=typeof t)for(var n in t)o.d(r,n,function(e){return t[e]}.bind(null,n));return r},o.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return o.d(t,\"a\",t),t},o.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},o.p=\"\"

ReferenceError: method is not defined
    at <REDACTED-PATH>/node_modules/async-array-buffer/build/es5/bundle.js:8:1484
    at <REDACTED-PATH>/node_modules/async-array-buffer/build/es5/bundle.js:2:65
    at Object.<anonymous> (<REDACTED-PATH>/node_modules/async-array-buffer/build/es5/bundle.js:5:2)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
```

> Node version: v8.12.0
> NPM version: 6.4.1
> "web-audio-beat-detector": "^7.0.1 "

Is there any way of using this inside a plain node script? Probably my setup isn't correct, can you point me into the right direction?
Thanks in advance!

**Comment by psturm** [comment]
Nevermind, please ignore my question. 
I'm not sure why i haven't thought of the obvious. There's no native support of `AudioContext` in node js :man_facepalming:

**Comment by chrisguttandin** [comment]
Hi @psturm, that's right.

The main thing used from the Web Audio API is the BiquadFilter. But since the expected input value is an AudioBuffer it is kind of required to use the Web Audio API to decode the audio as well.

Do you use another tool to decode the audio data?

**Comment by psturm** [comment]
Hey Chris,
thanks for the feedback! 

Within the browser i use normal AudioContext, which works super well with your package. Thanks for providing it!

Yesterday i quickly wanted to move some parts to a command line script, including detecting the bpms. 
First try importing your package resulted in this error, even before i moved the code to actually decode the audio, which would have been directly the next problem, i guess.
I opened this issue a bit prematurely, before i really thought about it. Sorry for that :smirk: 

For now i think the only option is to keep this within a browser context. But i'd be more than happy to get any hints on how to run this in a node CLI environment.

**Comment by chrisguttandin** [comment]
Would it be an option to run it with [puppeteer](https://github.com/GoogleChrome/puppeteer)?

**Comment by psturm** [comment]
I'll give it a try, thanks again for the nice and quick support!
