### ISSUE TITLE
Problem when import analyze module using bundle.js

### ISSUE THREAD

**Issue by Nhatmusic** [chrisguttandin/web-audio-beat-detector#233]
Hi chrisguttandin,

Thank you so much for the great application. I am really new to programming. In my application, I used bundle.js to import the web-audio-beat-detector module. However, it showed some error related to 

in standardized-audio-context/build/es5/bundle.js — line 286
in standardized-audio-context/build/es5/bundle.js — line 2
in standardized-audio-context/build/es5/bundle.js — line 5

Could you please tell me how to fix the problem? Thank you for your time and consideration.

**Comment by chrisguttandin** [comment]
Hi @Nhatmusic, thanks for your kind words.

I assume you used a regular `<script/>` tag to import web-audio-beat-detector. Unfortunately that doesn't work. This library is meant to be used with a bundler like [webpack](https://webpack.js.org) or [Rollup.js](https://rollupjs.org).

Alternatively you could use [jspm.io](https://jspm.io) to import a prebundled version like this:

```js
import { analyze } from 'https://dev.jspm.io/web-audio-beat-detector';
```

Issue #172 contains some more details about how do that.

I hope this helps.

**Comment by Nhatmusic** [comment]
Thank you for your quick response.
I tried these ways:
1. var webAudioBeatDetector = require('web-audio-beat-detector') using browserify i create a bundle.js
-> Have the error I mentioned above.
2. Use jspm.io by typing the following in my html:
 <script type=module>
        import('https://dev.jspm.io/web-audio-beat-detector').then(({ default: analyze }) => console.log(analyze));
    </script>
It does show the analyze as a function in my browser, however, when I use analyze in my js file. It said analyze is undefined.

**Comment by chrisguttandin** [comment]
Bundling this package with Browserify should normally work as well. I'm not sure why it doesn't work in your case.

I just doublechecked the syntax for importing the package from jspm.io. This works for me:

```html
<script type="module">
    import webAudioBeatDetector from 'https://dev.jspm.io/web-audio-beat-detector';

    console.log(webAudioBeatDetector.analyze);
 </script>
```

I hope it works for you as well.

**Comment by Nhatmusic** [comment]
Thank you so much for your support. I will try to find out the reason why it does not work in my case.

**Comment by chrisguttandin** [comment]
Hi @Nhatmusic, I just wanted to check back. Did you find a solution?

**Comment by Nhatmusic** [comment]
Hi Chrisguttandin, thank you for your consideration, I still do not find a
solution for the problem.

**Comment by chrisguttandin** [comment]
Oh, I'm sorry to hear that. Someone has a similar issue with another package of mine. Maybe some of the things pointed out there are helpful.

https://github.com/chrisguttandin/worker-timers/issues/281

**Comment by Nhatmusic** [comment]
Hi chrisguttandin,

My problem is solved. I used Browserify to export your module only as a global variable then I can include it in the <script> tag, cause I run my app in Node js, now I can include the module in my web page.
Thank you for your support.

**Comment by chrisguttandin** [comment]
Hi @Nhatmusic, thanks for reporting back. I'm happy that you found a solution, although I'm not sure if I fully understand how it works. :-)
