### ISSUE TITLE
SyntaxError: The requested module 'web-audio-beat-detector' does not provide an export named 'analyze'

### ISSUE THREAD

**Issue by Jbone187** [chrisguttandin/web-audio-beat-detector#246]
I using node 12 in --experimental-modules is that the issue and I need to be using it in the browser?

**Comment by chrisguttandin** [comment]
Hi @Jbone187, yes this module needs the browser runtime to work. It uses the Web Audio API to downsample and filter the audio and it uses a Web Worker to do the computation. Both things are not available when running on Node.js.

**Comment by Jbone187** [comment]
Darn lol thank you for the info

**Comment by chrisguttandin** [comment]
No problem.

By the way, I like the logos on your face mask. 👍
