### ISSUE TITLE
Cannot read property 'peaks' of undefined

### ISSUE THREAD

**Issue by mfbx9da4** [chrisguttandin/web-audio-beat-detector#88]
1. xhr get `audio/Tombo piano.mp3` (but tried with multiple), `responseType = "arraybuffer"`
2. `request.onload` => `context.decodeAudioData` => `buffer`
3. I am able to play the buffer fine via `source.buffer = buffer; source.start()`
4. `await guess(buffer)`

produces

```
module.js:69 Uncaught (in promise) Error: Cannot read property 'peaks' of undefined
    at Worker.onMessage (module.js:69)
```

**Comment by chrisguttandin** [comment]
Hi @mfbx9da4, thanks for reporting that issue. I just had a quick look at the source code and it might be possible that the algorithm can't detect any beats at all. That special case seems to be unhandled so far.

Are you able to upload the file you are using?

**Comment by mfbx9da4** [comment]
Yes sure, here are [three examples with no peaks](https://filebin.net/pfu2q24y39cuki0b)

Why would that be it can't detect any beats?

Also could you make the source file non-minified so I can see how it works better?

**Comment by chrisguttandin** [comment]
Many thanks for the example files. I updated the code to throw a meaningful error. The Tombo_piano.mp3 does indeed not contain any detectable beats. At least when using the algorithm used in this package, which is a relatively trivial one. You can find a link to an article describing the algorithm in the README.

This package is just a convenient version of the [web-audio-beat-detector-broker](https://github.com/chrisguttandin/web-audio-beat-detector-broker) and [web-audio-beat-detector-worker](https://github.com/chrisguttandin/web-audio-beat-detector-worker). It can be used without thinking about WebWorkers.

**Comment by mfbx9da4** [comment]
`Tombo_piano.mp3` is understandable but it's disappointing that no peaks could be found for  [Chambinho_do_Acordeon_e_Dominguinhos-h_z1x273cN8.mp3](https://filebin.net/pfu2q24y39cuki0b/Chambinho_do_Acordeon_e_Dominguinhos-h_z1x273cN8.mp3)

**Comment by chrisguttandin** [comment]
I'm sorry to hear that it doesn't work for you. The algorithm works best for electronic/hip-hop/pop music which contains a prominent and steady timed baseline. Maybe you get better results if you apply some preprocessing before using this package. I'm thinking of some dynamic processing which emphasizes the onsets. But I haven't tested that.

Please feel free to tweak the algorithm for [analyze()](https://github.com/chrisguttandin/web-audio-beat-detector-worker/blob/master/src/helpers/analyze.ts) or [guess()](https://github.com/chrisguttandin/web-audio-beat-detector-worker/blob/master/src/helpers/guess.ts). They could surely be better.

The built-in preprocessing happens here: https://github.com/chrisguttandin/web-audio-beat-detector-broker/blob/master/src/helpers/render.ts

**Comment by mfbx9da4** [comment]
Ok thanks for your help, I'll look into it if I get a chance and maybe try and port some stuff from [aubio](https://aubio.org/documentation)

**Comment by chrisguttandin** [comment]
Ok, I'm closing the issue because it was originally about the error message which is much more descriptive now.
